image: docker:19.03.11
services:
  - docker:19.03.11-dind
build:
  stage: build
  script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest -f WithoutJumanpp.Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  script:
    - apk update && apk add openssh
    - chmod 0400 "$SSH_KEY"
    - eval "$(ssh-agent)"
    - ssh-add "$SSH_KEY"
    - mkdir ~/.ssh/ && chmod 0700 ~/.ssh
    - ssh-keyscan -p22 -H $HOST > ~/.ssh/known_hosts
    - ssh -A -p22 ubuntu@$HOST 'bash -s' < deploy.sh
  only:
    - master
