default:

build:
  image: docker:19.03.11
  stage: build
  services:
    - docker:19.03.11-dind
  script: 
    - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - "docker build -t $CI_REGISTRY/tts-bot:latest ."
    - "docker push $CI_REGISTRY/tts-bot:latest"
deploy:
  stage: deploy
  script:
    - apk update && apk add openssh
    - chmod 0400 "$SSH_KEY"
    - eval "$(ssh-agent)"
    - ssh-add "$SSH_KEY"
    - mkdir ~/.ssh/ && chmod 0700 ~/.ssh
    - ssh-keyscan -p22 -H $HOST > ~/.ssh/known_hosts
    - ssh -A -p22 ubuntu@$HOST "$(docker stop tts-bot||true)&&$(docker rm tts-bot||true)&&docker run -d --name tts-bot --net tts-bot-net $CI_REGISTRY/tts-bot:latest"
  only:
    - master
