language: node_js
node_js:
  - 0.10

before_install:
  - npm install async
  - npm install doublearray
  - npm install zlibjs
  - npm install mocha
  - npm install chai
  - npm install jconv

script:
  - mocha -R spec --recursive
